### ISSUE TITLE
Añadir información básica sobre la aplicación

### ISSUE THREAD

**Issue by M4ss1ck** [adbenitez/deltachat-manual#16]
Podemos "robar" los 3 pequeños párrafos de [la página oficial en español](https://delta.chat/es/) e incluir el propio enlace

**Comment by adbenitez** [comment]
@M4ss1ck ya @gilbertolazaro92 hizo algo de eso en https://github.com/adbenitez/deltachat-manual/blob/main/docs/diferencias.md 

también la ayuda offline que viene con delta chat tiene un tema que es exactamente "¿Qué es Delta Chat?" donde explican bien, así que creo que es mejor no repetir eso aquí y enfocarnos en temas que no aparezcan ya en la ayuda y "preguntas frequentes" que vienen en la app, 

quizas añadir un punto aquí dandole a conocer a los usuarios la existencia de esa ayuda offline y recomendar leerla si quieren saber mas sobre delta chat y varios aspectos técnicos

**Comment by M4ss1ck** [comment]
había olvidado cerrar esto
